// Code generated by goctl. DO NOT EDIT.
package types

type CommonResponse struct {
	Code      int         `json:"code"`
	Msg       string      `json:"msg"`
	Timestamp int         `json:"timestamp"`
	Data      interface{} `json:"data"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
	Code     string `form:"code"`
	Key      string `form:"key"`
}

type LoginResponse struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	Realname  string `json:"realname"`
	Email     string `json:"email"`
	PhoneCode string `json:"phone_code"`
	Phone     string `json:"phone"`
	Avatar    string `json:"avatar"`
	Language  string `json:"language"`
	Token     string `json:"token"`
}

type ProfileRequest struct {
	Realname  string `form:"realname"`
	Email     string `form:"email"`
	PhoneCode string `form:"phone_code"`
	Phone     string `form:"phone"`
}

type RegisterRequest struct {
	Username  string `form:"username"`
	Password  string `form:"password"`
	Realname  string `form:"realname"`
	Email     string `form:"email"`
	PhoneCode string `form:"phone_code"`
	Phone     string `form:"phone"`
}

type SetPasswordRequest struct {
	Password    string `form:"password"`
	NewPassword string `form:"new_password"`
	RePassword  string `form:"re_password"`
}

type UserInfo struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	Realname  string `json:"realname"`
	Email     string `json:"email"`
	PhoneCode string `json:"phone_code"`
	Phone     string `json:"phone"`
	Avatar    string `json:"avatar"`
	Language  string `json:"language"`
}

type UserInfoResponse struct {
	Code      int      `json:"code"`
	Msg       string   `json:"msg"`
	Timestamp int      `json:"timestamp"`
	Data      UserInfo `json:"data"`
}
