// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-micro/api/article/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/article",
				Handler: ArticleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/article/delete",
				Handler: DeleteArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/article/detail",
				Handler: ArticleInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/article/disable",
				Handler: DisableArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/article/enable",
				Handler: EnableArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/article/save",
				Handler: SaveArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/home_article",
				Handler: HomeArticleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
