// Code generated by goctl. DO NOT EDIT.
package types

type ArticleInfo struct {
	Id      int64  `json:"id"`
	Catid   int64  `json:"catid"`
	Title   string `json:"title"`
	Info    string `json:"info"`
	Content string `json:"content"`
	Author  string `json:"author"`
	Status  int64  `json:"status"`
}

type ArticleInfoResponse struct {
	Code      int         `json:"code"`
	Msg       string      `json:"msg"`
	Timestamp int         `json:"timestamp"`
	Data      ArticleInfo `json:"data"`
}

type CommonResponse struct {
	Code      int         `json:"code"`
	Msg       string      `json:"msg"`
	Timestamp int         `json:"timestamp"`
	Data      interface{} `json:"data"`
}

type IdRequest struct {
	Id int64 `form:"id"`
}

type ListResponse struct {
	Code      int           `json:"code"`
	Msg       string        `json:"msg"`
	Timestamp int           `json:"timestamp"`
	Data      []ArticleInfo `json:"data"`
}

type SaveRequest struct {
	Id      int64  `form:"id,optional"`
	Catid   int64  `form:"catid,optional"`
	Title   string `form:"title"`
	Info    string `form:"info,optional"`
	Content string `form:"content,optional"`
	Author  string `form:"author,optional"`
	Status  int64  `form:"status,optional"`
}

type SearchRequest struct {
	Title    string `form:"title,optional"`
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
	Limit    int    `form:"limit,default=5000"`
}
