// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-micro/api/common/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ip",
				Handler: IpHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
